### ISSUE TITLE
Townywars does not end wars

### ISSUE THREAD

**Issue by CuboidCat** [karlovm/TownyWars#3]
So when the points of the town hit 0 the plugin will say the war ended and reward the winner, however, the war does not end and if you will someone again it will keep changing the points.

**Comment by karlovm** [comment]
Towny veison? latest.log? Spigot verison? Config.yml?

**Comment by CuboidCat** [comment]
I'm running towny advanced 0.96.3.0, spigot 1.16.3 latest,
[config.zip](https://github.com/karlovm/TownyWars/files/5584438/config.zip)

I need to do some more testing with my friend to get the log, so it will be a few hours.

**Comment by CuboidCat** [comment]
Here is the log
[latest.log](https://github.com/karlovm/TownyWars/files/5592679/latest.log)

**Comment by karlovm** [comment]
We don't work on 1.3.0. Use latest Towny version with 1.4.0

**Comment by CuboidCat** [comment]
I updated towny to 0.96.4.0 and nothing is different

**Comment by karlovm** [comment]
Fixed
